export const LIGHT_THEME = `
--background: white;
--primary: #3b40f6;
--outline: #777680;
--surface: #fffbff;
--on-surface: #1b1b1f;
--primary-container: #e0e0ff;
--on-primary: #ffffff;
--error: #ba1b1b;
--on-tertiary-container: #2e1125;
--tertiary-container: #ffd7ee;
--secondary: #5d5d72;
--on-secondary: #ffffff;`